### ISSUE TITLE
Battery 100% show empty icon

### ISSUE THREAD

**Issue by alexanderphoenix** [nwg-piotr/tint2-executors#4]
Hi, 

I have just switched over to tint2 and I found your scripts!
Very useful and well executed, thank you very much for sharing!

I have found a minor issue with the battery icon where it would show an empty battery when at 100%.

This is because it would remove 2 characters from bottom of the matched value, I'm assuming because of a percentage sign followed by a comma.
```
Battery 0: Full, 100%
Battery 0: Discharging, 100%, 03:20:21 remaining
Battery 0: Discharging, 99%, 03:06:16 remaining
Battery 0: Unknown, 99%
```
However in my case (on `5.4.52-1-MANJARO`) when at 100% it wouldn't have a comma at the end or any trailing information, as shown in the output above. 
This resulted in 2 characters being removed, instead of `100` I would get `10`, which is below the `15`% and therefore would show the empty battery icon.

I applied a quick fix as below:
```diff
diff --git a/battery-icon.sh b/battery-icon.sh
index 4b0db0b..0b7d29a 100755
--- a/battery-icon.sh
+++ b/battery-icon.sh
@@ -22,7 +22,11 @@ else
     if [[ "$state" == *"Unknown"* ]]; then
         level=${level::-1}
     else
-        level=${level::-2}
+        if [[ "$level" == "100%" ]]; then
+          level=${level::-1}
+        else
+          level=${level::-2}
+        fi
     fi
 fi
```

Hope this helps.

Have a good one,

Alex

**Comment by nwg-piotr** [comment]
Hi,

If I remember well, someone else reported this or similar issue, but I was unable to reproduce it on my machine. I'm on holiday at the moment, going to get back home next Friday. I'll take a closer look at the issue. Feel free to submit a PR, if your solution works. I never take any Linux machine along with me while going to the lakes, so I can't check it now.

Also: please tell me what WM or DE you use.

**Comment by alexanderphoenix** [comment]
Hi,

sorry for the delay in replying.
I did try to submit a PR but got denied (can't remember why). 
I'll give it another go shortly.

As for my WM, I use i3 :-)

**Comment by nwg-piotr** [comment]
Very well. I'm back home from holiday next Friday, and I'll take a closer look at the issue.

**Comment by nwg-piotr** [comment]
I have applied your fix here and in the [t2ec repository](https://github.com/nwg-piotr/t2ec). Actually this one is no longer maintained, and I even forgot I had had it; :) Thanks for your contribution!
